FROM python:3.10-slim

WORKDIR /app
COPY . /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip && \
    pip install kafka-python==2.0.2 && \
    pip install lz4==4.3.3 && \
    pip install cffi==1.16.0

CMD ["python3", "src/producer_ship.py"]