version: '2'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kafkanet
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafkanet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    hostname: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - kafkanet
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "ship_info:1:1"
  consumer_alert:
    image: consumer_alert
    container_name: consumer_alert
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka1:9092
    depends_on:
      - db
      - zookeeper
      - kafka1
    networks:
      - kafkanet
  producer_ship:
    image: producer_ship
    container_name: producer_ship
    depends_on:
      - db
      - zookeeper
      - kafka1
      - consumer_alert
    networks:
      - kafkanet
  consumer_ship:
    image: consumer_ship
    container_name: consumer_ship
    depends_on:
      - db
      - zookeeper
      - kafka1
      - consumer_alert
    networks:
      - kafkanet

volumes:
  postgres_data:

networks:
  kafkanet:
    external: true
    name: kafka-network
