version: '2'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
     - "3000:3000"
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - kafkanet

networks:
  kafkanet:
    external: true
    name: kafka-network